parameters:
    fc.constraint.not_blank.class: Fenrizbes\FormConstructorBundle\Item\Constraint\NotBlankConstraint
    fc.constraint.length.class:    Fenrizbes\FormConstructorBundle\Item\Constraint\LengthConstraint

services:
    fc.constraint.not_blank:
        class: %fc.constraint.not_blank.class%
        tags:  [ { name: fc.constraint, alias: not_blank } ]

    fc.constraint.length:
        class: %fc.constraint.length.class%
        tags:  [ { name: fc.constraint, alias: length } ]
