parameters:
    fc.constraint.not_blank.class:  Fenrizbes\FormConstructorBundle\Item\Constraint\NotBlankConstraint
    fc.constraint.length.class:     Fenrizbes\FormConstructorBundle\Item\Constraint\LengthConstraint
    fc.constraint.email.class:      Fenrizbes\FormConstructorBundle\Item\Constraint\EmailConstraint
    fc.constraint.one_of_set.class: Fenrizbes\FormConstructorBundle\Item\Constraint\OneOfSetConstraint
    fc.constraint.integer.class:    Fenrizbes\FormConstructorBundle\Item\Constraint\IntegerConstraint
    fc.constraint.float.class:      Fenrizbes\FormConstructorBundle\Item\Constraint\FloatConstraint
    fc.constraint.comparison.class: Fenrizbes\FormConstructorBundle\Item\Constraint\ComparisonConstraint
    fc.constraint.url.class:        Fenrizbes\FormConstructorBundle\Item\Constraint\UrlConstraint
    fc.constraint.characters.class: Fenrizbes\FormConstructorBundle\Item\Constraint\CharactersConstraint
    fc.constraint.count.class:      Fenrizbes\FormConstructorBundle\Item\Constraint\CountConstraint

services:
    fc.constraint.not_blank:
        class: %fc.constraint.not_blank.class%
        tags:  [ { name: fc.constraint, alias: not_blank } ]

    fc.constraint.length:
        class: %fc.constraint.length.class%
        tags:  [ { name: fc.constraint, alias: length } ]

    fc.constraint.email:
        class: %fc.constraint.email.class%
        tags:  [ { name: fc.constraint, alias: email } ]

    fc.constraint.one_of_set:
        class: %fc.constraint.one_of_set.class%
        tags:  [ { name: fc.constraint, alias: one_of_set } ]

    fc.constraint.integer:
        class: %fc.constraint.integer.class%
        tags:  [ { name: fc.constraint, alias: integer } ]

    fc.constraint.float:
        class: %fc.constraint.float.class%
        tags:  [ { name: fc.constraint, alias: float } ]

    fc.constraint.comparison:
        class: %fc.constraint.comparison.class%
        tags:  [ { name: fc.constraint, alias: comparison } ]

    fc.constraint.url:
        class: %fc.constraint.url.class%
        tags:  [ { name: fc.constraint, alias: url } ]

    fc.constraint.characters:
        class: %fc.constraint.characters.class%
        tags:  [ { name: fc.constraint, alias: characters } ]

    fc.constraint.count:
        class: %fc.constraint.count.class%
        tags:  [ { name: fc.constraint, alias: count } ]

# TODO:
#
# Дата
# Время
# Дата и время
# Сравнение даты и/или времени
# Сравнение даты с возрастом
#
# Изображение
# Файл