parameters:
    fc.constraint.not_blank.class:       Fenrizbes\FormConstructorBundle\Item\Constraint\NotBlankConstraint
    fc.constraint.length.class:          Fenrizbes\FormConstructorBundle\Item\Constraint\LengthConstraint
    fc.constraint.email.class:           Fenrizbes\FormConstructorBundle\Item\Constraint\EmailConstraint
    fc.constraint.one_of_set.class:      Fenrizbes\FormConstructorBundle\Item\Constraint\OneOfSetConstraint
    fc.constraint.integer.class:         Fenrizbes\FormConstructorBundle\Item\Constraint\IntegerConstraint
    fc.constraint.float.class:           Fenrizbes\FormConstructorBundle\Item\Constraint\FloatConstraint
    fc.constraint.comparison.class:      Fenrizbes\FormConstructorBundle\Item\Constraint\ComparisonConstraint
    fc.constraint.url.class:             Fenrizbes\FormConstructorBundle\Item\Constraint\UrlConstraint
    fc.constraint.characters.class:      Fenrizbes\FormConstructorBundle\Item\Constraint\CharactersConstraint
    fc.constraint.count.class:           Fenrizbes\FormConstructorBundle\Item\Constraint\CountConstraint
    fc.constraint.file.class:            Fenrizbes\FormConstructorBundle\Item\Constraint\FileConstraint
    fc.constraint.image.class:           Fenrizbes\FormConstructorBundle\Item\Constraint\ImageConstraint
    fc.constraint.datetime.class:        Fenrizbes\FormConstructorBundle\Item\Constraint\DateTimeConstraint
    fc.constraint.date_comparison.class: Fenrizbes\FormConstructorBundle\Item\Constraint\DateComparisonConstraint

services:
    fc.constraint.not_blank:
        class: %fc.constraint.not_blank.class%
        tags:  [ { name: fc.constraint, alias: not_blank } ]

    fc.constraint.length:
        class: %fc.constraint.length.class%
        tags:  [ { name: fc.constraint, alias: length } ]

    fc.constraint.email:
        class: %fc.constraint.email.class%
        tags:  [ { name: fc.constraint, alias: email } ]

    fc.constraint.one_of_set:
        class: %fc.constraint.one_of_set.class%
        tags:  [ { name: fc.constraint, alias: one_of_set } ]

    fc.constraint.integer:
        class: %fc.constraint.integer.class%
        tags:  [ { name: fc.constraint, alias: integer } ]

    fc.constraint.float:
        class: %fc.constraint.float.class%
        tags:  [ { name: fc.constraint, alias: float } ]

    fc.constraint.comparison:
        class: %fc.constraint.comparison.class%
        tags:  [ { name: fc.constraint, alias: comparison } ]

    fc.constraint.url:
        class: %fc.constraint.url.class%
        tags:  [ { name: fc.constraint, alias: url } ]

    fc.constraint.characters:
        class: %fc.constraint.characters.class%
        tags:  [ { name: fc.constraint, alias: characters } ]

    fc.constraint.count:
        class: %fc.constraint.count.class%
        tags:  [ { name: fc.constraint, alias: count } ]

    fc.constraint.file:
        class: %fc.constraint.file.class%
        tags:  [ { name: fc.constraint, alias: file } ]

    fc.constraint.image:
        class: %fc.constraint.image.class%
        tags:  [ { name: fc.constraint, alias: image } ]

    fc.constraint.datetime:
        class: %fc.constraint.datetime.class%
        tags:  [ { name: fc.constraint, alias: datetime } ]

    fc.constraint.date_comparison:
        class: %fc.constraint.date_comparison.class%
        tags:  [ { name: fc.constraint, alias: date_comparison } ]

# TODO:
# Сравнение даты/времени с выражениями "today", "-18 years" и т. п.