parameters:
    fc.admin.fields_types.text.class:     Fenrizbes\FormConstructorBundle\Form\Type\FcField\Admin\TextType
    fc.admin.fields_types.textarea.class: Fenrizbes\FormConstructorBundle\Form\Type\FcField\Admin\TextType

    fc.builder.fields_types.text.class:     Fenrizbes\FormConstructorBundle\Builder\FcField\TextBuilder
    fc.builder.fields_types.textarea.class: Fenrizbes\FormConstructorBundle\Builder\FcField\TextBuilder

    fc.fields_types:
        text:
            label:   fc.label.field_type.text
            class:   %fc.admin.fields_types.text.class%
            builder: %fc.builder.fields_types.text.class%
        textarea:
            label:   fc.label.field_type.textarea
            class:   %fc.admin.fields_types.textarea.class%
            builder: %fc.builder.fields_types.textarea.class%
