parameters:
    fc.field.text.class:     Fenrizbes\FormConstructorBundle\Item\Field\TextField
    fc.field.textarea.class: Fenrizbes\FormConstructorBundle\Item\Field\TextareaField
    fc.field.checkbox.class: Fenrizbes\FormConstructorBundle\Item\Field\CheckboxField
    fc.field.choice.class:   Fenrizbes\FormConstructorBundle\Item\Field\ChoiceField
    fc.field.hidden.class:   Fenrizbes\FormConstructorBundle\Item\Field\HiddenField
    fc.field.file.class:     Fenrizbes\FormConstructorBundle\Item\Field\FileField
    fc.field.datetime.class: Fenrizbes\FormConstructorBundle\Item\Field\DateTimeField
    fc.field.date.class:     Fenrizbes\FormConstructorBundle\Item\Field\DateField
    fc.field.time.class:     Fenrizbes\FormConstructorBundle\Item\Field\TimeField

services:
    fc.field.text:
        class: %fc.field.text.class%
        tags:  [ { name: fc.field, alias: text } ]

    fc.field.textarea:
        class: %fc.field.textarea.class%
        tags:  [ { name: fc.field, alias: textarea } ]

    fc.field.checkbox:
        class: %fc.field.checkbox.class%
        tags:  [ { name: fc.field, alias: checkbox } ]

    fc.field.choice:
        class: %fc.field.choice.class%
        tags:  [ { name: fc.field, alias: choice } ]

    fc.field.hidden:
        class: %fc.field.hidden.class%
        tags:  [ { name: fc.field, alias: hidden } ]

    fc.field.file:
        class: %fc.field.file.class%
        tags:  [ { name: fc.field, alias: file } ]

    fc.field.datetime:
        class: %fc.field.datetime.class%
        tags:  [ { name: fc.field, alias: datetime } ]

    fc.field.date:
        class: %fc.field.date.class%
        tags:  [ { name: fc.field, alias: date } ]

    fc.field.time:
        class: %fc.field.time.class%
        tags:  [ { name: fc.field, alias: time } ]

# TODO:
#
# Чойс из БД
# Чойс "Другое" с полем свободного ввода
#
# Флажок с принятием некоторых условий
#
# Слайдер
# Слайдер с диапазоном
#
# КЛАДР

# ГЛОБАЛЬНО:
# Разбивка формы на шаги - специальным полем-разделителем
# Возможность добавления пользователем сайта полей или групп полей (еще один телефон/еще контакнтные данные и т. п.) - чекбокс "коллекция"
# Программирование поведений