parameters:
    fc.field.text.class:     Fenrizbes\FormConstructorBundle\Item\Field\TextField
    fc.field.textarea.class: Fenrizbes\FormConstructorBundle\Item\Field\TextareaField
    fc.field.checkbox.class: Fenrizbes\FormConstructorBundle\Item\Field\CheckboxField
    fc.field.choice.class:   Fenrizbes\FormConstructorBundle\Item\Field\ChoiceField
    fc.field.hidden.class:   Fenrizbes\FormConstructorBundle\Item\Field\HiddenField
    fc.field.file.class:     Fenrizbes\FormConstructorBundle\Item\Field\FileField

services:
    fc.field.text:
        class: %fc.field.text.class%
        tags:  [ { name: fc.field, alias: text } ]

    fc.field.textarea:
        class: %fc.field.textarea.class%
        tags:  [ { name: fc.field, alias: textarea } ]

    fc.field.checkbox:
        class: %fc.field.checkbox.class%
        tags:  [ { name: fc.field, alias: checkbox } ]

    fc.field.choice:
        class: %fc.field.choice.class%
        tags:  [ { name: fc.field, alias: choice } ]

    fc.field.hidden:
        class: %fc.field.hidden.class%
        tags:  [ { name: fc.field, alias: hidden } ]

    fc.field.file:
        class: %fc.field.file.class%
        tags:  [ { name: fc.field, alias: file } ]

# TODO:
#
# Чойс из БД
# Чойс "Другое" с полем свободного ввода
#
# Дата
# Время
# Дата и время
#
# Флажок с принятием некоторых условий
#
# Слайдер
# Слайдер с диапазоном
#
# КЛАДР

# ГЛОБАЛЬНО:
# Разбивка формы на шаги
# Программирование поведений
# Зависимость отображения полей от значения другого поля (есть дети - указывай, нет - не надо)
# Возможность добавления пользователем сайта полей или групп полей (еще один телефон/еще контакнтные данные и т. п.)