parameters:
    fc.field.text.class:     Fenrizbes\FormConstructorBundle\Item\Field\TextField
    fc.field.textarea.class: Fenrizbes\FormConstructorBundle\Item\Field\TextareaField

services:
    fc.field.text:
        class: %fc.field.text.class%
        tags:  [ { name: fc.field, alias: text } ]

    fc.field.textarea:
        class: %fc.field.textarea.class%
        tags:  [ { name: fc.field, alias: textarea } ]
