parameters:
    fc.listener.send_to_email.class: Fenrizbes\FormConstructorBundle\Item\Listener\SendToEmailListener

services:
    fc.listener.send_to_email:
        class:     %fc.listener.send_to_email.class%
        arguments: [ @mailer, @templating ]
        tags:      [ { name: fc.listener, alias: send_to_email } ]
