services:
    fenrizbes_form_constructor.admin.form:
        class: Fenrizbes\FormConstructorBundle\Admin\SonataAdmin\FcFormAdmin
        arguments:
            - ~
            - Fenrizbes\FormConstructorBundle\Propel\Model\Form\FcForm
            - FenrizbesFormConstructorBundle:SonataAdmin\FcFormAdmin
        tags:
            -
                name:         sonata.admin
                manager_type: propel
                group:        fc.label.admin
                label:        fc.label.admin.form
        calls:
            - [ setFcDefaults,        [ %fc.defaults% ] ]
            - [ setFieldChain,        [ @fc.field.chain ] ]
            - [ setTranslationDomain, [ FenrizbesFormConstructorBundle ] ]
            - [ setTemplate,          [ edit, FenrizbesFormConstructorBundle:SonataAdmin\FcForm:edit.html.twig ] ]
            - [ setTemplate,          [ show, FenrizbesFormConstructorBundle:SonataAdmin\FcForm:show.html.twig ] ]
