services:
    twig.extension.fc:
        class: Fenrizbes\FormConstructorBundle\Twig\FcTwigExtension
        calls:
            - [ setFormService,     [ @fc.form ] ]
            - [ setFieldChain,      [ @fc.field.chain ] ]
            - [ setConstraintChain, [ @fc.constraint.chain ] ]
            - [ setListenerChain,   [ @fc.listener.chain ] ]
        tags:
            - { name: twig.extension }
